version: '2'
services:

  chrome:
    build: .
    privileged: true
    container_name: docker_chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444" # Selenium Hub port
      - "5900:5900" # VNC port
